### ISSUE TITLE
Toilet Causes crash

### ISSUE THREAD

**Issue by Thotlax** [ekfvoddl3536/OniMods#10]
Since the Nov. QOL update your [Vanilla + DLC] Eco-friendly Toilet & Farm+ V3.0 crashes when you save your game if you have built the toilet. The rest of the buildings are fine. 

[Player.log](https://github.com/user-attachments/files/17894388/Player.log)

TypeLoadException: Could not resolve type with token 01000047 from typeref (expected class 'Worker' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')

System.Reflection.MonoMethodInfo.GetMethodInfo (System.IntPtr handle) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributes () (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
System.MonoCustomAttrs.GetPseudoCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Boolean inherit) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
System.Reflection.RuntimeMethodInfo.GetCustomAttributes (System.Boolean inherit) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
KSerialization.Helper.GetSerializationMethods (System.Type type, System.Type type_a, System.Type type_b, System.Type type_c, System.Reflection.MethodInfo& method_a, System.Reflection.MethodInfo& method_b, System.Reflection.MethodInfo& method_c) (at <199beda79a0545e18356f69e28ee38c2>:0)
KSerialization.SerializationTemplate..ctor (System.Type type) (at <199beda79a0545e18356f69e28ee38c2>:0)
KSerialization.Manager.GetSerializationTemplate (System.Type type) (at <199beda79a0545e18356f69e28ee38c2>:0)
KSerialization.Serializer.SerializeTypeless (System.Object obj, System.IO.BinaryWriter writer) (at <199beda79a0545e18356f69e28ee38c2>:0)
SaveLoadRoot.SaveWithoutTransform (System.IO.BinaryWriter writer) (at <96bf83e479e841629616de31cacb5606>:0)
SaveLoadRoot.Save (System.IO.BinaryWriter writer) (at <96bf83e479e841629616de31cacb5606>:0)
SaveManager.Write (Tag key, System.Collections.Generic.List`1[T] value, System.IO.BinaryWriter writer) (at <96bf83e479e841629616de31cacb5606>:0)
SaveManager.Save (System.IO.BinaryWriter writer) (at <96bf83e479e841629616de31cacb5606>:0)
SaveLoader.Save (System.IO.BinaryWriter writer) (at <96bf83e479e841629616de31cacb5606>:0)
(wrapper dynamic-method) SaveLoader.SaveLoader.Save_Patch7(SaveLoader,string,bool,bool)
PauseScreen.DoSave (System.String filename) (at <96bf83e479e841629616de31cacb5606>:0)
PauseScreen+<>c__DisplayClass25_0.<OnSave>b__0 () (at <96bf83e479e841629616de31cacb5606>:0)
ConfirmDialogScreen.OnSelect_OK () (at <96bf83e479e841629616de31cacb5606>:0)
KButton.SignalClick (KKeyCode btn) (at <199beda79a0545e18356f69e28ee38c2>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <199beda79a0545e18356f69e28ee38c2>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <6405a4abeb6c490388904d755e3f6782>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <6405a4abeb6c490388904d755e3f6782>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U53-642695-SCD

**Comment by ekfvoddl3536** [comment]
It's probably been resolved...

**Comment by ekfvoddl3536** [comment]
This issue is probably resolved. If you experience the same issue again, please open an issue again.
