### ISSUE TITLE
EcoFriendlyToliet의 AutoPurifyWashsink의 소음을 줄일 수 있을까요?

### ISSUE THREAD

**Issue by geonmo** [ekfvoddl3536/OniMods#2]
안녕하세요? 슈퍼코믹님 모드를 즐겨 쓰고 있는 사용자입니다.

해당 모드 중에 AutoPurifyWashsink의 경우 전기를 넣으면 빨리 정제되는 기능이 있는데 

이 기능을 사용할 때 소리가 너무 커서 좁은 공간에 배치하면 쓰기가 좋지 않은거 같습니다.

혹시 해당 소음 문제를 해결해주실 수 있으신지요?

res.AudioSize = "small";

나 아예 소리 자체를 다른 거로 바꾸는 것은 어떠신가 해서 연락 드립니다.

해당 기능을 제가 직접 수정해서 넣고 싶었으나 mod_info.yaml가 공개된 것이 없어서 기존 세이브 파일이 깨질 거 같아 요청 드립니다.

**Comment by ekfvoddl3536** [comment]
의견 감사합니다 :)
다음 게임 진행 도우미 V2.0+ 업데이트 작업때 AutoPurifyWashink의 오디오 크기 이슈도 해결하도록 하겠습니다

업데이트는 6월 중~7월 초에 진행될 것으로 예상되오니 참고부탁드리겠습니다 ^_^

**Comment by ekfvoddl3536** [comment]
해당 문제는 전선 연결 및 전력량 인식 관련에서 사운드 재생으로 발생한 것으로 확인됐으며, 최신 버전에서 해결되었습니다 :)
