### ISSUE TITLE
Lazy Saver+ breaks world gen

### ISSUE THREAD

**Issue by Sgt-Imalas** [ekfvoddl3536/OniMods#3]
[Player-prev(5).log](https://github.com/ekfvoddl3536/OniMods/files/11127378/Player-prev.5.log)
after world gen is finished, the world gen thread crashes.

also please IL-Merge your dlls

**Comment by ekfvoddl3536** [comment]
Lazy Saver+ is experimental and is no longer being developed.  
  
Parallelizing the save logic requires more research.
