### ISSUE TITLE
Wild Farm Tile

### ISSUE THREAD

**Issue by alexander-cg** [ekfvoddl3536/OniMods#5]
Hi, this mod is great, thanks!

I did notice an issue with the "Wild Farm Tile'. After I create it and plant a seed, if I reload my game I have to make it 'not harvestable' otherwise the dupes will try to harvest the plant. can this be fixed?

**Comment by ekfvoddl3536** [comment]
I was able to reproduce this issue in the latest version. 'Plant seeds in the tile, disable automatic harvesting, then save and load the game. After loading, you will see that it has been reactivated.'  
  
This issue has been resolved. Such problems no longer reproduce.  
    
Thank you for reporting the bug :)

**Comment by ekfvoddl3536** [comment]
I will consider the issue resolved and close the issue. If the issue occurs again, please re-open it.
