### ISSUE TITLE
Please update DLC 

### ISSUE THREAD

**Issue by Kadircan9090** [ekfvoddl3536/OniMods#9]
Please update DLC Spaced Out

https://steamcommunity.com/sharedfiles/filedetails/?id=1796508081&searchtext=super

**Comment by ekfvoddl3536** [comment]
Unfortunately, Magic Script MOD has been deprecated.  
  
There are several reasons for this, but the biggest one is that I completely lost the source code for the MOD, which is the main reason why I can't continue updating it.  
  
Still, thanks for finding my MOD.  
  
That's a long term issue that needs to be resolved slowly, and I'm not planning any future updates for this MOD yet, so I'll close this issue.
